# roi: [404, 488, 500, 1400] # ../cowling_images/data_cam3_to_cam5/0_screwing_position.bmp
roi: [755, 661, 400, 1000] # ../cowling_images/data_cam3_to_cam5/0_with_cowling.bmp
# roi: [734, 626, 1660, 1040] # ../cowling_images/data_cam3_to_cam5/0_without_cowling.bmp


Gaussian_params: 7 # filter size
Threshold_params: 
  - 100 # threshold
  - 255 # maxval
Canny_params:
  - 80 # lower bound
  - 200 # upper bound



HoughLine_params_edges: 100 # threshold for hough_line() function call using edge image as input
HoughLine_params_contours: 100 # threshold for hough_line() function call using contour as input


