Gaussian_params: 7  # filter size
Threshold_params: 
  - 250             # threshold
  - 255             # maxval
Canny_params:
  - 80              # lower bound
  - 200             # upper bound



HoughLine_params: 
  d_rho: 1          # 1 pixel
  d_theta: 1        # in degrees, not in radians
  threshold: 110    # threshold for HoughLine() function call 
  min_theta: 0      # in degrees, not in radians  
  max_theta: 180    # in degrees, not in radian



